### ISSUE TITLE
NIH: add MeSH labels

### ISSUE THREAD

**Issue by mindrones** [nestauk/nesta#101]
See:
- https://github.com/nestauk/nesta/issues/81#issuecomment-498218507
- #102

**Comment by jaklinger** [comment]
@georgerichardson Has finished processing these. Hopefully these will be added by the end of the week, or earlier.

**Comment by georgerichardson** [comment]
Had a bit of a disaster with this. Turns out the NIH delete your files after a short time after processing. Having to run everything again. It's hard to say when this will be done as the speed is variable, I suspect due to how heavily the service is being used by others Optimistically end of this week, otherwise middle of the next.

**Comment by mindrones** [comment]
Closed by #112
